import json
import base64
import time

with open("yt_cookies.json", "r") as f:
    cookies = json.load(f)

with open("yt_cookies.txt", "w") as f:
    f.write("# Netscape HTTP Cookie File\n")
    f.write("# https://curl.se/docs/http-cookies.html\n")
    f.write("# This file was generated by yt-dlp. Edit at your own risk.\n\n")
    for c in cookies:
        domain = c.get("domain", "")
        flag = "TRUE" if domain.startswith(".") else "FALSE"
        path = c.get("path", "/")
        secure = "TRUE" if c.get("secure", False) else "FALSE"
        expiration = str(int(c.get("expires", 0) or 0))
        name = c.get("name", "")
        value = c.get("value", "")
        f.write(f"{domain}\t{flag}\t{path}\t{secure}\t{expiration}\t{name}\t{value}\n")

print("Converted cookies to Netscape format: yt_cookies.txt")
